branch-defaults:
  master:
    environment: uno-classifieds-prod
    group_suffix: null
environment-defaults:
  uno-classifieds-prod:
    branch: null
    repository: null
global:
  application_name: uno_classifieds
  default_ec2_keyname: ec2KeyPair
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Passenger with Ruby
    2.4 running on 64bit Amazon Linux/2.6.1
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
